// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsawlrjmsuduoyfypngj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzYXdscmptc3VkdW95ZnlwbmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDcyMzgsImV4cCI6MjA2NDkyMzIzOH0.kkgksfU-LfQyfI-CEyU5N-uCA-HM1i3f7qT0av7XhF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);